# Generated by Django 4.2.3 on 2023-07-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True, blank=True)),
                ('img_url', models.ImageField(upload_to='images/')),
                ('age', models.IntegerField()),
                ('bio', models.TextField(max_length=850)),
            ],
        ),
    ]
